(function(){window.CG=window.CG||{};const C=()=>window.CG.Content; const rand=a=>a[Math.floor(Math.random()*a.length)]; const Q=C().QUINTET.map(q=>q.key); let S, app;
function fresh(opts){ const theatre=rand(C().THEATRES); const players=opts.players.slice(0,4).map((p,i)=>({name:p.name,human:p.human,role:rand(C().ROLES),pos:1,score:0,done:false,rank:0,quint:Object.fromEntries(Q.map(k=>[k,0])),color:['#2F6BFF','#E8439B','#7C4DFF','#FF7A1A'][i]})); S={players,dice:opts.dice||1,theatre,turn:0,rolled:0,finished:0,quint:Object.fromEntries(Q.map(k=>[k,0])),tiles:{ladders:{},holes:{},trophy:{},diamond:{},surprise:{},note:{}},lastCard:null,zone:-1,exactFails:Object.fromEntries(players.map((_,i)=>[i,0])),locked:false,log:[]}; buildBoard(); }
function reservePath(res,a,b){ const lo=Math.min(a,b),hi=Math.max(a,b); for(let x=lo;x<=hi;x++) if(res.has(x)) return false; for(let x=lo;x<=hi;x++) res.add(x); return true;}
function buildBoard(){const res=new Set([1,100]); function col(n){return (n-1)%10;} let tries=0; while(Object.keys(S.tiles.ladders).length<6&&tries++<1000){let a=2+Math.floor(Math.random()*70), up=a+10*(1+Math.floor(Math.random()*3)); if(up<100&&col(a)==col(up)&&reservePath(res,a,up)) S.tiles.ladders[a]=up;} tries=0; while(Object.keys(S.tiles.holes).length<6&&tries++<1000){let a=25+Math.floor(Math.random()*73), down=a-10*(1+Math.floor(Math.random()*3)); if(down>1&&col(a)==col(down)&&reservePath(res,down,a)) S.tiles.holes[a]=down;} scatter('trophy',4,res);scatter('diamond',5,res);scatter('surprise',6,res);scatter('note',7,res); let trap=95+Math.floor(Math.random()*5); if(!res.has(trap)){S.tiles.surprise[trap]=true;res.add(trap);} }
function scatter(kind,n,res){while(Object.keys(S.tiles[kind]).length<n){let x=2+Math.floor(Math.random()*97); if(!res.has(x)){S.tiles[kind][x]=true;res.add(x);}}}
function boust(n){ let row=Math.floor((n-1)/10), col=(n-1)%10; if(row%2) col=9-col; return {gridColumn:col+1, gridRow:10-row};}
function draw(){ app.innerHTML=`<header><div><h1>Common Ground <span>The Long Road</span></h1><p>${S.theatre.icon} ${S.theatre.name}: ${S.theatre.blurb}</p></div><div class="toggles"><button id="music">${window.CG.Audio.isOn()?'🔇':'🎵'} Music</button><button id="voice">${window.CG.Narrate.isOn()?'🔇':'🔊'} Narration</button><button id="new">New</button></div></header><main><section id="board"></section><aside><div class="panel"><h2>Turn</h2><p id="status"></p><button id="roll">Roll dice</button></div><div class="panel"><h2>Standings</h2><div id="stand"></div></div><div class="panel"><h2>UN 2.0 Quintet</h2><div id="quint"></div></div><div id="card"></div></aside></main>`; board(); side(); app.querySelector('#roll').onclick=roll; app.querySelector('#new').onclick=()=>window.CG.Setup.render(app,start); app.querySelector('#music').onclick=()=>{window.CG.Audio.music(!window.CG.Audio.isOn());draw();}; app.querySelector('#voice').onclick=()=>{window.CG.Narrate.toggle(!window.CG.Narrate.isOn());draw();}; speak(C().STORY.opening.replace('{theatre}',S.theatre.name)); }
function board(){const b=app.querySelector('#board'); for(let n=1;n<=100;n++){const d=document.createElement('div');d.className='cell';d.id='sq'+n;Object.assign(d.style,boust(n));let mark=''; if(S.tiles.ladders[n])mark='🪜'; if(S.tiles.holes[n])mark='🕳️'; if(S.tiles.trophy[n])mark='🏆'; if(S.tiles.diamond[n])mark='💎'; if(S.tiles.surprise[n])mark='🎲'; if(S.tiles.note[n])mark='📘'; d.innerHTML=`<small>${n}</small><b>${mark}</b>`; b.appendChild(d);} renderTokens(); lines();}
function lines(){const b=app.querySelector('#board'); const svg=document.createElementNS('http://www.w3.org/2000/svg','svg'); svg.classList.add('lines'); b.appendChild(svg); function center(n){const p=boust(n);return {x:(p.gridColumn-0.5)*10,y:(p.gridRow-0.5)*10};} function line(a,bn,c,w){let A=center(+a),B=center(bn);let l=document.createElementNS(svg.namespaceURI,'line');l.setAttribute('x1',A.x+'%');l.setAttribute('y1',A.y+'%');l.setAttribute('x2',B.x+'%');l.setAttribute('y2',B.y+'%');l.setAttribute('stroke',c);l.setAttribute('stroke-width',w);l.setAttribute('stroke-linecap','round');svg.appendChild(l);} Object.entries(S.tiles.ladders).forEach(([a,b])=>line(a,b,'#4da3ff',6)); Object.entries(S.tiles.holes).forEach(([a,b])=>line(a,b,'#24e67a',8));}
function renderTokens(){document.querySelectorAll('.token').forEach(x=>x.remove()); S.players.forEach((p,i)=>{let sq=app.querySelector('#sq'+p.pos); if(!sq)return; let t=document.createElement('span'); t.className='token'; t.style.background=p.color; t.textContent=i+1; t.title=`${p.name} - ${p.role.name}`; sq.appendChild(t);});}
function side(){app.querySelector('#status').innerHTML=`${S.players[S.turn].name}'s turn ${S.players[S.turn].human?'':'(AI)'}`; app.querySelector('#stand').innerHTML=S.players.map((p,i)=>`<div class="person" style="border-color:${p.color}"><b>${p.name}</b><span>${p.role.icon} ${p.role.name}, ${p.role.aff}</span><span>Square ${p.pos} · ${p.score} pts ${p.done?'· 🏁 #'+p.rank:''}</span></div>`).join(''); app.querySelector('#quint').innerHTML=C().QUINTET.map(q=>`<div class="q"><span>${q.icon} ${q.name}</span><meter min="-5" max="8" value="${S.quint[q.key]}"></meter><b>${S.quint[q.key]}</b></div>`).join(''); if(!S.players[S.turn].human&&!S.locked) setTimeout(roll,700);}
function roll(){ if(S.locked) return; let p=S.players[S.turn]; if(p.done){next();return;} S.locked=true; window.CG.Audio.sfx.roll(); let total=0, rolls=[]; for(let i=0;i<S.dice;i++){let r=1+Math.floor(Math.random()*6);rolls.push(r);total+=r;} if(p.pos>90&&S.exactFails[S.turn]>=8) total=100-p.pos; let target=p.pos+total; if(target>100){S.exactFails[S.turn]++; target=100-(target-100);} if(target===100-p.pos) S.exactFails[S.turn]=0; app.querySelector('#status').textContent=`${p.name} rolled ${rolls.join(' + ')} = ${total}`; walk(p,target,()=>resolve(target,rolls));}
function walk(p,target,cb){let dir=target>=p.pos?1:-1; let id=setInterval(()=>{ if(p.pos===target){clearInterval(id);cb();return;} p.pos+=dir; window.CG.Audio.sfx.step(); renderTokens(); window.CG.Audio.setProgress(p.pos/100); zoneBeat(p.pos);},120);}
function zoneBeat(pos){let z=Math.floor((pos-1)/25); if(z!==S.zone){S.zone=z; speak(C().STORY.zones[z]||'');}}
function drawCard(deck,tag){let pool=deck.filter(c=>c!==S.lastCard); let weighted=[]; pool.forEach(c=>{let w=1+(c.tag===tag?3:0)+(S.theatre.tags.includes(c.tag)?2:0); for(let i=0;i<w;i++) weighted.push(c);}); let c=rand(weighted.length?weighted:pool); S.lastCard=c; return c;}
function quintFor(tag){return C().TAG_MAP[tag]||null;}
function addScore(pi,pts,tag){let p=S.players[pi]; p.score=Math.max(0,p.score+pts); const q=quintFor(tag); if(q){let delta=pts>0?1:-1; S.quint[q]+=delta; p.quint[q]+=delta;}}
function cardHTML(c,extra=''){return `<div class="card"><h2>${c.icon} ${c.title}</h2><p>${fill(c.why)}</p><p><b>Field fact:</b> ${c.fact}</p>${extra}<button id="read">🔊 Read aloud</button><button id="continue">Continue</button></div>`;}
function fill(s){let p=S.players[S.turn];return s.replaceAll('{role}',p.role.name).replaceAll('{aff}',p.role.aff).replaceAll('{theatre}',S.theatre.name);} function speak(t,cb){window.CG.Narrate.speak(t,cb);} 
function showCard(c,extra,cb){const box=app.querySelector('#card'); box.innerHTML=cardHTML(c,extra); box.querySelector('#read').onclick=()=>speak(`${c.title}. ${fill(c.why)} ${c.fact}`); box.querySelector('#continue').onclick=()=>{box.innerHTML='';cb();}; speak(`${c.title}. ${fill(c.why)} ${c.fact}`); if(!S.players[S.turn].human) setTimeout(()=>box.querySelector('#continue')&&box.querySelector('#continue').click(),1600);}
function resolve(pos,rolls){let i=S.turn,p=S.players[i]; if(pos===100){p.done=true;p.rank=++S.finished; window.CG.Audio.sfx.win(); if(S.finished===S.players.length) return end(); S.locked=false; next(); return;}
 if(S.tiles.ladders[pos]){let c=drawCard(C().LADDER_CARDS,p.role.tag); addScore(i,3,c.tag); window.CG.Audio.sfx.ladder(); showCard(c,`<p class="effect">Climb from ${pos} to ${S.tiles.ladders[pos]} · +3</p>`,()=>{p.pos=S.tiles.ladders[pos];renderTokens();S.locked=false;next(rolls);});return;}
 if(S.tiles.holes[pos]){let c=drawCard(C().SNAKE_CARDS,p.role.tag); addScore(i,-2,c.tag); window.CG.Audio.sfx.hole(); showCard(c,`<p class="effect bad">Slide from ${pos} to ${S.tiles.holes[pos]} · -2</p>`,()=>{p.pos=S.tiles.holes[pos];renderTokens();S.locked=false;next(rolls);});return;}
 if(S.tiles.trophy[pos]){let c=drawCard(C().TROPHY_CARDS,p.role.tag); addScore(i,5,c.tag); window.CG.Audio.sfx.gem(); showCard(c,'<p class="effect">+5 and roll again</p>',()=>{S.locked=false;side();});return;}
 if(S.tiles.diamond[pos]){let c=drawCard(C().DIAMOND_CARDS,p.role.tag); addScore(i,4,c.tag); window.CG.Audio.sfx.gem(); showCard(c,'<p class="effect">+4 and hop forward 3</p>',()=>{p.pos=Math.min(100,p.pos+3);renderTokens();S.locked=false;resolve(p.pos,rolls);});return;}
 if(S.tiles.surprise[pos]){let c=drawCard(C().SURPRISE_CARDS,p.role.tag); if(pos>=95)c=C().SURPRISE_CARDS.find(x=>x.effect&&x.effect.tilt==='bad')||c; showCard(c,'<p class="effect">Surprise movement</p>',()=>{let e=c.effect||{move:0}; if(e.finish)p.pos=100; else if(e.start)p.pos=1; else p.pos=Math.max(1,Math.min(100,p.pos+(e.move||0))); renderTokens(); S.locked=false; resolve(p.pos,rolls);});return;}
 if(S.tiles.note[pos]){let note=rand(C().FIELD_NOTES); app.querySelector('#card').innerHTML=`<div class="card"><h2>📘 Field note</h2><p>${note}</p><button id="continue">Continue</button></div>`; speak(note); app.querySelector('#continue').onclick=()=>{app.querySelector('#card').innerHTML='';S.locked=false;next(rolls);}; if(!p.human)setTimeout(()=>app.querySelector('#continue')?.click(),1200);return;}
 S.locked=false; next(rolls);}
function next(rolls=[]){let doubles=S.dice===2&&rolls[0]===rolls[1]; if(doubles&&!S.players[S.turn].done){window.CG.Audio.sfx.gem(); side(); return;} do{S.turn=(S.turn+1)%S.players.length;}while(S.players[S.turn].done); side();}
function end(){let champs=[]; champs.push(`Speed: ${S.players.find(p=>p.rank===1).name}`); let max=Math.max(...S.players.map(p=>p.score)); champs.push(`Perseverance: ${S.players.filter(p=>p.score===max).map(p=>p.name).join(', ')}`); C().QUINTET.forEach(q=>{let m=Math.max(...S.players.map(p=>p.quint[q.key])); if(m>0) champs.push(`${q.name}: ${S.players.filter(p=>p.quint[q.key]===m).map(p=>p.name).join(', ')}`);}); app.querySelector('#card').innerHTML=`<div class="card win"><h2>🏁 Finished mandate</h2><p>${C().STORY.win}</p><h3>Champions</h3><ul>${champs.map(x=>`<li>${x}</li>`).join('')}</ul><button onclick="location.reload()">Play again</button></div>`; speak(C().STORY.win+' Champions. '+champs.join('. ')); side();}
function start(opts){app=document.getElementById('app');fresh(opts);draw();}
window.CG.Game={start};})();